app/models.py
# -*- coding: UTF-8 -*-

from datetime import datetime

from werkzeug.security import generate_password_hash, check_password_hash
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from flask.ext.login import UserMixin, AnonymousUserMixin

from flask import current_app
from . import mongo, login_manager

class Permission:
    FOLLOW = 0x01
    POST = 0x02
    MODERATE = 0x04
    ADMINISTER = 0x08

class Role:
    USER = Permission.FOLLOW |\
           Permission.POST
    MODERATOR = Permission.FOLLOW |\
                Permission.POST |\
                Permission.MODERATE
    ADMINISTRATOR = 0xff

class User(UserMixin):

    def __init__(self, username):
        self.username = username

    def get_id(self):
        return self.username

    def can(self, permissions):
        return self.role is not None and \
               (int(self.role) & permissions) == permissions

    def is_administrator(self):
        return self.can(Permission.ADMINISTER)

    @property
    def role(self):
        doc = mongo.db.users.find_one({'_id': self.username},
                                      {'_id':0, 'role': 1})
        try:
            return doc['role']
        except KeyError, e:
            return None

    @role.setter
    def role(self, role):
        mongo.db.users.update_one({'_id': self.username},
                                  {'$set': { 'role': role}})

    @property
    def confirmed(self):
        doc = mongo.db.users.find_one({'_id': self.username},
                                      {'_id':0, 'confirmed': 1})
        try:
            return doc['confirmed']
        except KeyError, e:
            return False

    @property
    def email(self):
        doc = mongo.db.users.find_one({'_id': self.username},
                                      {'_id':0, 'email': 1})
        try:
            return doc['email']
        except KeyError, e:
            return False

    @staticmethod
    def get_user(username):
        user = mongo.db.users.find_one({'_id': username})
        return user if user else None

    @staticmethod
    def add_user(username, email, password, role):
        mongo.db.users.insert_one({'_id': username, 'email': email,
                             'password_hash': generate_password_hash(password),
                             'role': role})

    @staticmethod
    def email_exists(email):
        user = mongo.db.users.find_one({'email': email})
        return True if user else False

    @staticmethod
    def validate_login(password_hash, password):
        return check_password_hash(password_hash, password)

    @staticmethod
    def generate_confirmation_token(username=None, expiration=3600):
        s = Serializer(current_app.config['SECRET_KEY'], expiration)
        return s.dumps({'confirm': username})

    @staticmethod
    def confirm(username, token):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            data = s.loads(token)
        except:
            return False
        if data.get('confirm') != username:
            return False
        mongo.db.users.update_one({'_id': username},
                                  {'$set': { 'confirmed': True}})
        return True


class Saying(object):

    tags = [('funny', 'مضحك'),
            ('adult', '18+'),
            ]

    @staticmethod
    def add_saying(text, added_by, origins=[], tags=[]):
        doc = { 'text' : text,
                'added_by': added_by,
                'date_created': datetime.utcnow(),
                'origins': origins, 
                'tags': tags,
                'approved': False}
        mongo.db.sayings.insert_one(doc)

    @staticmethod
    def get_country_names(language='english'):
        countries = list(mongo.db.countries.aggregate([ 
                          { '$unwind' : '$country' },
                          { '$match' : { 'country.language': language } },
                          { '$group' : { '_id' : '$country.name'} }
                          ]))
        return [(x['_id'], x['_id']) for x in countries]

    @staticmethod
    def get_tags():
        return Saying.tags

class AnonymousUser(AnonymousUserMixin):
    def can(self, permissions):
        return False
    def is_administrator(self):
        return False

login_manager.anonymous_user = AnonymousUser

@login_manager.user_loader
def load_user(username):
    u = mongo.db.users.find_one({"_id": username})
    if not u:
        return None
    return User(u['_id'])

app/__init__.py
from flask import Flask
from flask.ext.bootstrap import Bootstrap
from flask.ext.pymongo import PyMongo
from flask.ext.mail import Mail
from flask.ext.moment import Moment
from flask.ext.login import LoginManager
from config import config
import sys

reload(sys)
sys.setdefaultencoding('utf-8')

bootstrap = Bootstrap()
mongo = PyMongo()
mail = Mail()
moment = Moment()

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    app.jinja_env.trim_blocks = True
    config[config_name].init_app(app)

    bootstrap.init_app(app)
    mongo.init_app(app)
    mail.init_app(app)
    moment.init_app(app)
    login_manager.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views
from ..models import Permission
from .. import mongo
 

@main.app_context_processor
def inject_permissions():
    return dict(Permission=Permission)

app/main/views.py
# -*- coding: UTF-8 -*-

from flask import render_template, flash
from flask.ext.login import login_user, logout_user, login_required, \
    current_user

from flask.ext.wtf import Form
from wtforms import StringField, BooleanField, SubmitField, SelectMultipleField
from wtforms.validators import Required, Length, Email, Regexp, EqualTo
from wtforms import ValidationError

from . import main
from .. import mongo
# from .forms import SayingForm
from ..models import Permission, Saying
from ..decorators import permission_required


@main.route('/')
def index():
    sayings = list(mongo.db.sayings.find())
    return render_template('index.html', sayings=sayings)


@main.route('/post-saying', methods=['GET', 'POST'])
@login_required
@permission_required(Permission.POST)
def post_saying():

	class SayingForm(Form):
	    text = StringField('Saying', validators=[Length(20, 140)])
	    origins = SelectMultipleField('Origins', choices=Saying.get_country_names('english'))
	    # origins = SelectMultipleField('Origins', choices=Saying.get_tags())
	    tags = SelectMultipleField('Tags', choices=Saying.get_tags())
	    submit = SubmitField('Post Saying')

	form = SayingForm()
	if form.validate_on_submit():
		text = form.text.data
		user = current_user.get_id()
		origins = form.origins.data if form.origins.data else []
		tags = form.tags.data if form.tags.data else []
		Saying.add_saying(
			            text=text,
			            added_by=user,
			            origins=origins,
			            tags=tags)
		flash("saying successfully added")
		return redirect(request.args.get('next') or url_for('main.index'))
	return render_template('post_saying.html', form=form)

app/templates/base.html
{% extends "bootstrap/base.html" %}
{% from 'macros.html' import set_active %}


{% set active_page = active_page|default('home') -%}

{% block metas %}
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
<meta name="description" content="">
<meta name="author" content="">
{% endblock %}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static', filename='style.css')}}">
{% endblock %}

{% block title %}أمثال{% endblock %}


{% block navbar %}
<nav class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <a class="navbar-brand navbar-right navbar-title" href="#">Project name</a>
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav  navbar-right">
            <li {{ set_active('home', active_page) }}><a href="{{ url_for('main.index') }}">Home</a></li>
            <li {{ set_active('about', active_page) }}><a href="#about">About</a></li>
            <li {{ set_active('contact', active_page) }}><a href="#contact">Contact</a></l #}i>
        </ul>
         <ul class="nav navbar-nav navbar-left">
            {% if current_user.is_authenticated %}
            <li><a href="{{ url_for('auth.logout') }}">Log Out</a></li>
            <li><a href="{{ url_for('main.post_saying') }}">Post Saying</a></li>
            {% else %}
            <li {{ set_active('login', active_page) }}><a href="{{ url_for('auth.authentication') }}">Log In</a></li>
            {% endif %}
         </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>
{% endblock %}

{% block content %}
<div class="container text-right">

<div class="row">
    <div class="col-sm-8 col-sm-push-2">

    {% for category, message in get_flashed_messages(with_categories=true) %}

    <div class="alert {% if category %}{{ category }}{% else %}alert-warning{% endif %}" role='alert'>
        <div class="row">
            <div class='col-sm-1'>
                <button type="button" class="close" data-dismiss="alert">&times;</button>
            </div>
            <div class='col-sm-11'>
                {{ message }}
            </div>
        </div>
    </div>
    {% endfor %}

    </div><!-- /.sayings -->
</div><!-- /.row -->

{% block page_content %}{% endblock %}

</div><!-- /.container -->
{% endblock %}

{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block page_content %}

<div class="row">

    <div class="col-sm-8 col-sm-push-2 sayings">

        {% for saying in sayings %}
        {% set date_added = saying._id.generation_time -%}
        <div class="saying-entry">
            <p class="saying-meta">{{ moment(date_added).format('ll',) }}
                      by <a href="#">{{ saying.added_by }}</a></p>
            <p class="lead saying-text">
                {{ saying.text }}
            </p>
        </div><!-- /.saying-entry -->
        {% endfor %}

    </div><!-- /.sayings -->

</div><!-- /.row -->
{% endblock %}

app/templates/macros.html
{% macro set_active(id, active_page) -%}
    {% if id == active_page %} class="active"{% endif %}
{%- endmacro %}

app/templates/post_saying.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% set active_page = "" %}

{% block title %}Port Saying{% endblock %}

{% block page_content %}

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="page-header">
            <h1>New Saying</h1>
        </div>
        {{ wtf.quick_form(form) }}
    </div>
</div>

{% endblock %}